---
abstract: 'Helper for Twitter Bootstrap and TT view which builds a skeleton web site'
author:
  - 'Ferruccio Zamuner <nonsolosoft@diff.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Helper-View-Bootstrap
no_index:
  directory:
    - inc
    - share
requires:
  Catalyst: '5.7'
  Catalyst::View::TT: 0
  File::ShareDir: 0
  Template: 0
  perl: 5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: '0.0006'
